# 150 perguntas variadas sobre Valorant
perguntas_todas = [
    # ========== AGENTES (50) ==========
    {"pergunta": "Qual agente usa a habilidade Paranoia?", "resposta": "omen"},
    {"pergunta": "Qual agente pode se tornar invisível com a Dimensional Drift?", "resposta": "yoru"},
    {"pergunta": "Qual agente usa câmeras de vigilância?", "resposta": "cypher"},
    {"pergunta": "Qual agente vem do Brasil?", "resposta": "raze"},
    {"pergunta": "Qual agente pode ressuscitar aliados?", "resposta": "sage"},
    {"pergunta": "Qual agente usa um arco e flecha?", "resposta": "sova"},
    {"pergunta": "Qual é o nome da ultimate da Raze?", "resposta": "showstopper"},
    {"pergunta": "Qual agente usa fogo nas habilidades?", "resposta": "phoenix"},
    {"pergunta": "Qual agente controla estrelas no mapa?", "resposta": "astra"},
    {"pergunta": "Qual agente vem da Coreia do Sul?", "resposta": "jett"},
    {"pergunta": "Qual agente usa uma mochila de foguetes?", "resposta": "raze"},
    {"pergunta": "Qual agente usa veneno nas habilidades?", "resposta": "viper"},
    {"pergunta": "Qual agente tem uma habilidade chamada Blade Storm?", "resposta": "jett"},
    {"pergunta": "Qual agente vem da Alemanha?", "resposta": "killjoy"},
    {"pergunta": "Qual agente instala torretas e minas?", "resposta": "killjoy"},
    {"pergunta": "Qual é o nome da ultimate do Omen?", "resposta": "from the shadows"},
    {"pergunta": "Qual agente usa habilidades de gelo (Slow Orb)?", "resposta": "sage"},
    {"pergunta": "Qual agente é mexicana e curte sangue?", "resposta": "reyna"},
    {"pergunta": "Qual agente é russo?", "resposta": "sova"},
    {"pergunta": "Qual agente é americana e usa lobo astral?", "resposta": "skye"},
    {"pergunta": "Qual agente é australiana?", "resposta": "skye"},
    {"pergunta": "Qual agente é filipina e usa eletricidade?", "resposta": "neon"},
    {"pergunta": "Qual agente é um robô?", "resposta": "kay/o"},
    {"pergunta": "Qual agente suprime habilidades inimigas?", "resposta": "kay/o"},
    {"pergunta": "Qual agente é francês e usa armadilhas com headhunter?", "resposta": "chamber"},
    {"pergunta": "Qual agente é turca e vê pesadelos?", "resposta": "fade"},
    {"pergunta": "Qual agente é mexicano e tem criaturas companheiras?", "resposta": "gekko"},
    {"pergunta": "Qual é o nome do companheiro 'minhoca' do Gekko?", "resposta": "wingman"},
    {"pergunta": "Qual agente é indiano e usa controle de água?", "resposta": "harbor"},
    {"pergunta": "Qual agente é não-binário e escocês?", "resposta": "clove"},
    {"pergunta": "Qual agente é mexicano e foi adicionado em 2025?", "resposta": "tejo"},
    {"pergunta": "Qual agente é sul-coreana e adicionada em 2025?", "resposta": "waylay"},
    {"pergunta": "Qual agente é americano e fundador da Protocolo?", "resposta": "brimstone"},
    {"pergunta": "Qual agente britânico tem ulti chamada Run It Back?", "resposta": "phoenix"},
    {"pergunta": "Qual agente é norueguesa e captura inimigos com Annihilation?", "resposta": "deadlock"},
    {"pergunta": "Qual agente chinês cria uma cópia de si mesmo?", "resposta": "iso"},
    {"pergunta": "Qual agente americana usa portais espelho?", "resposta": "vyse"},
    {"pergunta": "Qual é o tipo (classe) da Sage?", "resposta": "sentinela"},
    {"pergunta": "Qual é o tipo da Jett?", "resposta": "duelista"},
    {"pergunta": "Qual é o tipo do Omen?", "resposta": "controlador"},
    {"pergunta": "Qual é o tipo do Sova?", "resposta": "iniciador"},
    {"pergunta": "Qual agente tem habilidade Recon Bolt?", "resposta": "sova"},
    {"pergunta": "Qual agente tem habilidade Tailwind (dash)?", "resposta": "jett"},
    {"pergunta": "Qual agente tem habilidade Snake Bite?", "resposta": "viper"},
    {"pergunta": "Qual agente tem habilidade Cybercage?", "resposta": "cypher"},
    {"pergunta": "Qual agente tem habilidade Nanoswarm?", "resposta": "killjoy"},
    {"pergunta": "Qual é a ulti do Cypher?", "resposta": "neural theft"},
    {"pergunta": "Qual é a ulti da Viper?", "resposta": "viper's pit"},
    {"pergunta": "Qual é a ulti do Brimstone?", "resposta": "orbital strike"},
    {"pergunta": "Qual é a ulti da Reyna?", "resposta": "empress"},
    {"pergunta": "Qual é a ulti do KAY/O?", "resposta": "null/cmd"},

    # ========== MAPAS (25) ==========
    {"pergunta": "Qual mapa tem dois portais de teletransporte?", "resposta": "bind"},
    {"pergunta": "Qual é o nome do mapa ambientado em Marrocos?", "resposta": "bind"},
    {"pergunta": "Qual mapa fica debaixo d'água em Lisboa?", "resposta": "pearl"},
    {"pergunta": "Qual mapa tem teleporte em forma de tirolesa?", "resposta": "icebox"},
    {"pergunta": "Qual mapa tem 3 sites (A, B e C)?", "resposta": "haven"},
    {"pergunta": "Qual mapa fica no Japão e tem corda Kabuki?", "resposta": "split"},
    {"pergunta": "Qual mapa é ambientado no Texas?", "resposta": "ascent"},
    {"pergunta": "Qual mapa tem portas mecânicas controladas por botão?", "resposta": "ascent"},
    {"pergunta": "Qual mapa tem cordas (ascenders) no Kremlin?", "resposta": "icebox"},
    {"pergunta": "Qual mapa fica em Veneza, Itália?", "resposta": "ascent"},
    {"pergunta": "Qual mapa tem o nome de uma fortaleza?", "resposta": "fracture"},
    {"pergunta": "Qual mapa é em formato de H?", "resposta": "fracture"},
    {"pergunta": "Qual mapa fica no Brasil?", "resposta": "abyss"},
    {"pergunta": "Qual mapa não tem bordas (é um abismo)?", "resposta": "abyss"},
    {"pergunta": "Qual mapa fica na Tailândia?", "resposta": "lotus"},
    {"pergunta": "Qual mapa tem portas rotativas e 3 sites?", "resposta": "lotus"},
    {"pergunta": "Qual mapa foi removido e voltou em 2024?", "resposta": "haven"},
    {"pergunta": "Qual mapa fica em uma estação espacial?", "resposta": "breeze"},
    {"pergunta": "Qual mapa é em uma ilha caribenha?", "resposta": "breeze"},
    {"pergunta": "Qual mapa foi adicionado com a Neon e fica em Manila?", "resposta": "pearl"},
    {"pergunta": "Qual mapa fica em uma estação de pesquisa polar?", "resposta": "icebox"},
    {"pergunta": "Qual mapa tem o nome de um portão (gateway)?", "resposta": "sunset"},
    {"pergunta": "Qual mapa fica em Los Angeles?", "resposta": "sunset"},
    {"pergunta": "Qual mapa é o mais antigo de todos?", "resposta": "bind"},
    {"pergunta": "Qual mapa tem o nome de um corredor (corridor)?", "resposta": "corrode"},

    # ========== ARMAS (30) ==========
    {"pergunta": "Qual arma é a sniper mais cara do jogo?", "resposta": "operator"},
    {"pergunta": "Qual é o rifle mais popular do jogo?", "resposta": "vandal"},
    {"pergunta": "Qual rifle dá headshot 1 hit a qualquer distância?", "resposta": "vandal"},
    {"pergunta": "Qual rifle é mais preciso e tem 25 balas no pente?", "resposta": "phantom"},
    {"pergunta": "Quanto custa a Vandal?", "resposta": "2900"},
    {"pergunta": "Quanto custa a Operator?", "resposta": "4700"},
    {"pergunta": "Quanto custa o Phantom?", "resposta": "2900"},
    {"pergunta": "Qual é a pistola gratuita do jogo?", "resposta": "classic"},
    {"pergunta": "Qual pistola tem o maior dano por tiro?", "resposta": "sheriff"},
    {"pergunta": "Qual pistola é uma 'desert eagle' do Valorant?", "resposta": "sheriff"},
    {"pergunta": "Qual SMG custa 1600 créditos?", "resposta": "spectre"},
    {"pergunta": "Qual é a shotgun mais usada?", "resposta": "judge"},
    {"pergunta": "Qual arma pesada custa 5000 créditos?", "resposta": "odin"},
    {"pergunta": "Qual é a metralhadora mais comum?", "resposta": "ares"},
    {"pergunta": "Qual rifle custa 1600 créditos?", "resposta": "bulldog"},
    {"pergunta": "Qual rifle tem 3 disparos no modo zoom?", "resposta": "bulldog"},
    {"pergunta": "Qual rifle de tiro único custa 1600 e é semi-auto?", "resposta": "guardian"},
    {"pergunta": "Qual sniper é mais barata que a Operator?", "resposta": "marshal"},
    {"pergunta": "Qual sniper adicionada em 2023 substitui a Marshal em alguns casos?", "resposta": "outlaw"},
    {"pergunta": "Quantas balas tem a Marshal?", "resposta": "5"},
    {"pergunta": "Quantas balas a Outlaw tem?", "resposta": "2"},
    {"pergunta": "Qual é a pistola mais cara?", "resposta": "sheriff"},
    {"pergunta": "Qual pistola pode dar tiro alternativo de longa distância?", "resposta": "ghost"},
    {"pergunta": "Qual pistola dispara 3 balas ao mesmo tempo?", "resposta": "shorty"},
    {"pergunta": "Qual SMG é mais cara que a Spectre?", "resposta": "ares"},
    {"pergunta": "Qual é a faca padrão do jogo? (nome do tipo)", "resposta": "tactical knife"},
    {"pergunta": "Quanto custa a Stinger?", "resposta": "1100"},
    {"pergunta": "Qual SMG dispara muito rápido e custa 1100?", "resposta": "stinger"},
    {"pergunta": "Quanto custa a Judge?", "resposta": "1850"},
    {"pergunta": "Qual shotgun é barata e custa 800?", "resposta": "bucky"},

    # ========== JOGABILIDADE / MECÂNICAS (25) ==========
    {"pergunta": "Quantos jogadores tem cada time no Valorant?", "resposta": "5"},
    {"pergunta": "Quantos rounds vence o time pra ganhar a partida normal?", "resposta": "13"},
    {"pergunta": "Quantos créditos dá pra perder um round?", "resposta": "1900"},
    {"pergunta": "Quantos créditos dá pra vencer um round?", "resposta": "3000"},
    {"pergunta": "Qual o valor máximo de créditos que dá pra ter?", "resposta": "9000"},
    {"pergunta": "Quanto tempo dura um round?", "resposta": "100 segundos"},
    {"pergunta": "Quanto tempo a Spike leva pra explodir?", "resposta": "45 segundos"},
    {"pergunta": "Quanto tempo leva pra plantar a Spike?", "resposta": "4 segundos"},
    {"pergunta": "Quanto tempo leva pra defusar a Spike?", "resposta": "7 segundos"},
    {"pergunta": "Quantos rounds tem um Overtime (prorrogação)?", "resposta": "2"},
    {"pergunta": "Quanto dano um headshot da Vandal causa?", "resposta": "160"},
    {"pergunta": "Quanto custa um escudo completo (heavy shield)?", "resposta": "1000"},
    {"pergunta": "Quanto custa um escudo leve (light shield)?", "resposta": "400"},
    {"pergunta": "Quantos pontos de vida tem cada jogador?", "resposta": "100"},
    {"pergunta": "Quantos pontos o escudo completo dá?", "resposta": "50"},
    {"pergunta": "Quantos pontos o escudo leve dá?", "resposta": "25"},
    {"pergunta": "Como se chama a fase de comprar armas?", "resposta": "buy phase"},
    {"pergunta": "Quantos segundos dura o buy phase?", "resposta": "30"},
    {"pergunta": "Qual o nome da spike (em inglês)?", "resposta": "spike"},
    {"pergunta": "Quantos pontos de orbe ultimate o agente começa a partida?", "resposta": "0"},
    {"pergunta": "Quantos orbes ultimate tem em cada mapa (normalmente)?", "resposta": "2"},
    {"pergunta": "Quantos pontos cada orbe ultimate dá?", "resposta": "1"},
    {"pergunta": "Quantos rounds vai pro lado dos defensores antes de trocar?", "resposta": "12"},
    {"pergunta": "Em que round trocam de lado normalmente?", "resposta": "13"},
    {"pergunta": "Como se chama o modo onde se compra o que quiser?", "resposta": "custom"},

    # ========== LORE / HISTÓRIA (20) ==========
    {"pergunta": "Qual é o nome da organização vilã no lore?", "resposta": "kingdom"},
    {"pergunta": "Qual é o nome da organização heroína?", "resposta": "vp"},
    {"pergunta": "Qual o nome do recurso místico do Valorant?", "resposta": "radianite"},
    {"pergunta": "Como se chamam pessoas com poderes no lore?", "resposta": "radiantes"},
    {"pergunta": "Qual evento criou os radiantes?", "resposta": "first light"},
    {"pergunta": "Em que ano (dentro do lore) o jogo se passa?", "resposta": "2050"},
    {"pergunta": "Qual o nome da Terra paralela do lore?", "resposta": "terra-2"},
    {"pergunta": "Qual agente é o líder da Protocolo VP?", "resposta": "brimstone"},
    {"pergunta": "Qual ano o Valorant foi lançado?", "resposta": "2020"},
    {"pergunta": "Quem desenvolve Valorant?", "resposta": "riot games"},
    {"pergunta": "Qual o nome do diretor de jogo do Valorant?", "resposta": "andy ho"},
    {"pergunta": "Qual cor representa o Valorant?", "resposta": "vermelho"},
    {"pergunta": "Qual é a competição mundial de Valorant?", "resposta": "champions"},
    {"pergunta": "Qual time brasileiro venceu a Champions 2022?", "resposta": "loud"},
    {"pergunta": "Qual sigla designa a liga internacional de Valorant?", "resposta": "vct"},
    {"pergunta": "Qual time venceu a primeira Champions (2021)?", "resposta": "acend"},
    {"pergunta": "Em que ano a LOUD foi campeã mundial?", "resposta": "2022"},
    {"pergunta": "Qual liga é a do Brasil/Américas?", "resposta": "americas"},
    {"pergunta": "Quem é o IGL famoso da LOUD?", "resposta": "saadhak"},
    {"pergunta": "Qual jogador da LOUD usa nick aspas?", "resposta": "aspas"},
]
